- still sussing out corner cases/races/exceptions - if a START'ed process ENDs and we never see its END message, it   effectively is dead weight that consumes headroom in concurrency.   so create the concept of "$disappeared_pids" and perform a `kill -0'   test on every PID in the currently running list, moving things   to disappeared if they fail that kill 	- to handle the condition where they have a sent an END 	  to the fifo, ended, but the cursor in IPC_MASTER is 	  at the kill -0 stage, which fails, allow "END" messages 	  to remove PIDs from the disappeared list and decrement 	  counters appropriately
- for removing a word from a list, instead of iterating over
  every word in the list, switch to iterating over every target
  word and then leverage a case statement with patterns for each
  location the word can be in the list (front, middle, end, not present).
  since the list is of unique words, this is a good fit.

- create an ABORT message, used by IPC_CHILD()'ren who saw the
  teardown flag before reaching START state.

- fix broken dash(1) compat by removing arithmetic the arithmetic
  evaluation against IPC_CONCURRENCY, burning a variable for the
  math that was in there, and just doing a regular test(1)-like
  eval.

- convert all IPC_CHILD and IPC_END fifo message sends from one-shot
  attempts into until-success loops with an incremental backoff to handle
  (hopefully) all cases like:

dash: echo: I/O error
cannot create $tmpdir/fifo: Interrupted system call

diff --git a/lib/misc/ipc b/lib/misc/ipc
--- a/lib/misc/ipc
+++ b/lib/misc/ipc
@@ -174,18 +174,24 @@ IPC_MASTER()
 {
 	local funcname=IPC_MASTER
 
-	local currently_running=0
-	local currently_pending=0
-	local currently_signaled=0
+	local currently_pending=0 # we've seen its PENDING, but have not removed child_lock
+	local currently_running=0 # we've seen its START, but not its END
+	local currently_signaled=0 # we removed child_lock, but have not seen a subsequent START
+	local lifetime_disappeared=0
+	local disappeared_pids # we saw their START, didn't see their END, and they're gone
+	local flag
 	local greatest_concurrency=0 
 	local info
 	local lifetime_ended_total=0
 	local lifetime_started_total=0
 	local message=INIT
+	local running_pids _running_pids # no pending_pids because they don't have their own PIDs yet
 	local pid pids
 	local teardown=0
-	local var var2
+	local var
 	local wait_requestors _wait_requestors
+
+	trap 'warnx "$funcname(): trapped SIGPIPE' PIPE
 
 	if ! pid=$(current_pid); then
 		warnx "$funcname(): failed to get current PID"
@@ -200,21 +206,92 @@ IPC_MASTER()
 	while :; do
 
 		message=READ
-		# # debug 1 "$funcname(): [$message] beginning to read fifo"
+		debug 1 "$funcname(): [$message] beginning to read fifo"
+
 		while read message pid info; do
+
+			# sanity check $pid for messages it matters
+			# $message itself is sanity checked in the main case statement
+			case $message in
+			END | START | WAIT)
+				if ! isdigit "$pid"; then
+					warnx "$funcname(): [$message] message contains invalid \$pid: '$pid'"
+					continue
+				fi
+				;;
+			esac
 
 			while :; do
 
-				# debug 1 "$funcname(): [READ] fifo: '$pid' -> [$message]"
+				debug 1 "$funcname(): [READ] fifo: '$pid' -> [$message], optional info: [$info]"
 				# debug 13 "$funcname(): [$message] logging message from '$pid'"
 				# echo "$pid $message $funcname" >>"ipcdir/recvlog"
 
 				case $message in
+				ABORT)
+					# a pending child saw teardown before successfully START'ing
+					currently_pending=$(( currently_pending - 1 ))
+					;;
 				END)
-					# end message includes return code of child, otherwise
+					flag=0
+					# remove $pid from $running_pids, set flag if found
+					case $running_pids in
+					$pid)
+						flag=1
+						running_pids=""
+						;;
+					$pid" "*)
+						flag=1
+						running_pids=${running_pids#$pid }
+						;;
+					*" "$pid)
+						flag=1
+						running_pids=${running_pids% $pid}
+						;;
+					*" "$pid" "*)
+						flag=1
+						var=${running_pids#* $pid } # RHS
+						running_pids=${running_pids% $pid *} # LHS
+						running_pids="$running_pids $var"
+						;;
+					esac
+					if [ $flag -eq 0 ]; then
+						# $pid not found in $running_pids, check $disappeared_pids
+						flag=0
+						case $disappeared_pids in
+						"")
+							;;
+						$pid)
+							flag=1
+							disappeared_pids=""
+							;;
+						$pid" "*)
+							flag=1
+							disappeared_pids=${disappeared_pids#$pid }
+							;;
+						*" "$pid)
+							flag=1
+							disappeared_pids=${disappeared_pids% $pid}
+							;;
+						*" "$pid" "*)
+							flag=1
+							var=${disappeared_pids#* $pid } # RHS
+							disappeared_pids=${disappeared_pids% $pid *} # LHS
+							disappeared_pids="$disappeared_pids $var"
+							;;
+						esac
+						if [ $flag -eq 0 ]; then
+							warnx "$funcname(): [$message] \$pid '$pid' not found in \$running_pids or \$disappeared_pids"
+						else
+							lifetime_disappeared=$(( lifetime_disappeared - 1 )) # found one
+						fi
+					else
+						# $pid was found in $running_pids
+						currently_running=$(( currently_running - 1 ))
+						lifetime_ended_total=$(( lifetime_ended_total + 1 ))
+					fi
+					# end message includes return code of child, which is otherwise
 					# unavailable b/c they were &'d..
-					currently_running=$(( currently_running - 1 ))
-					lifetime_ended_total=$(( lifetime_ended_total + 1 ))
 					if ! isdigit "$info"; then
 						warnx "$funcname(): [$message] non-numeric return value '$info' from \$pid: '$pid'"
 					elif [ $info -ne 0 ]; then
@@ -227,13 +304,30 @@ IPC_MASTER()
 					currently_pending=$(( currently_pending + 1 ))
 					;;
 				START)
-					currently_running=$(( currently_running + 1 ))
+					flag=0
+					# add to running_pids list if not duplicate
+					case $running_pids in
+					"")
+						running_pids=$pid
+						;;
+					$pid | $pid" "* | *" "$pid | *" "$pid" "* )
+						# only item | already in front | .. end | .. middle
+						flag=1
+						;;
+					*)
+						# wasn't present
+						running_pids="$running_pids $pid"
+						;;
+					esac
+					if [ $flag -eq 0 ]; then
+						currently_running=$(( currently_running + 1 ))
+						currently_signaled=$(( currently_signaled - 1 ))
+						lifetime_started_total=$(( lifetime_started_total + 1 ))
+					fi
 					if [ $currently_running -gt $greatest_concurrency ]; then
 						# informational
 						greatest_concurrency=$currently_running
 					fi
-					currently_signaled=$(( currently_signaled - 1 ))
-					lifetime_started_total=$(( lifetime_started_total + 1 ))
 					;;
 				STATUS)
 					if ! cat >"$IPC_DIR/status" <<- EOT
@@ -241,10 +335,13 @@ IPC_MASTER()
 						currently_running: "$currently_running"
 						currently_signaled: "$currently_signaled"
 						greatest_concurrency: "$greatest_concurrency"
+						lifetime_disappeared: "$lifetime_disappeared"
 						lifetime_ended_total: "$lifetime_ended_total"
 						lifetime_started_total: "$lifetime_started_total"
 						teardown mode: "$teardown"
 						wait_requestors: "$wait_requestors"
+						running_pids: "$running_pids"
+						disappeared_pids: "$disappeared_pids"
 						EOT
 					then
 						warnx "$funcname(): [$message] unable to update status file '$IPC_DIR/status'"
@@ -256,19 +353,31 @@ IPC_MASTER()
 						warnx "$funcname(): [$message] failed to set \$IPC_TEARDOWN file: '$IPC_TEARDOWN'"
 					fi
 					# debug 3 "$funcname(): [$message] adding \$pid '$pid' to \$wait_requestors '$wait_requestors'"
-					# XXX check for dupes?
-					if [ -z "$wait_requestors" ]; then
+					flag=0
+					case $wait_requestors in
+					"")
 						wait_requestors=$pid
-					else
+						;;
+					$pid | $pid" "* | *" "$pid | *" "$pid" "* )
+						# only item | already in front | .. end | .. middle
+						flag=1
+						;;
+					*)
+						# wasn't present
 						wait_requestors="$wait_requestors $pid"
+						;;
+					esac
+					if [ $flag -ne 0 ]; then
+						warnx "$funcname(): [$message] ignoring duplicate message from \$pid: '$pid'"
 					fi
-					# debug 4 "$funcname(): [$message] \$wait_requestors is now '$wait_requestors', ensure addition \$pid: '$pid'"
 					;;
 				*)
 					warnx "$funcname(): [$message] ERROR: unknown message"
 					return 1
 					;;
 				esac
+
+				# at this point it's safe to reuse the $pid parameter if we need to
 
 				message=WORK
 				# debug 2 "$funcname(): [$message] looking for work"
@@ -297,7 +406,8 @@ IPC_MASTER()
 					break 3
 				fi
 
-				if (( (currently_running + currently_signaled) >= IPC_CONCURRENCY )); then
+				var=$(( currently_running + currently_signaled ))
+				if [ $var -ge $IPC_CONCURRENCY ]; then
 					# debug 2 "$funcname(): [$message] at concurrency limit: '$IPC_CONCURRENCY', looping"
 					break
 				fi
@@ -307,7 +417,7 @@ IPC_MASTER()
 				fi
 
 				if [ -e "$IPC_CHILD_LOCK" ]; then
-					# debug 37 "$funcname(): [$message] attempting to remove child lock: '$IPC_CHILD_LOCK'"
+					debug 37 "$funcname(): [$message] attempting to remove child lock: '$IPC_CHILD_LOCK'"
 					if ! rm -f "$IPC_CHILD_LOCK"; then
 						warnx "$funcname(): [$message] unable to remove pending child lock: '$IPC_CHILD_LOCK'"
 						return 1
@@ -328,38 +438,98 @@ IPC_MASTER()
 			# debug 12 "$funcname(): [$message] \$lifetime_ended_total: '$lifetime_ended_total'"
 
 			message=READ
-			# debug 1 "$funcname(): [$message] reading fifo"
+			debug 1 "$funcname(): [$message] reading fifo"
 			continue 
 
 		done <"$IPC_FIFO"
 
 		message=RECOVER
-		# debug 7 "$funcname(): [$message] fell out of the loop because no pending fifo writes to read"
+		debug 7 "$funcname(): [$message] fell out of the loop because no pending fifo writes to read"
 		# debug 10 "$funcname(): [$message] \$currently_running: '$currently_running'"
 		# debug 12 "$funcname(): [$message] \$lifetime_started_total: '$lifetime_started_total'"
 		# debug 12 "$funcname(): [$message] \$lifetime_ended_total: '$lifetime_ended_total'"
 		
-		if [ $currently_pending -gt 0 ]; then
-			continue
-		fi
 		if [ $currently_running -gt 0 ]; then
-			# debug 7 "$funcname(): [$message] still children running"
+			# GC disappeared children:
+			_disappeared_pids=""
+			flag=0
+			for pid in $running_pids; do
+				if kill -0 "$pid"; then
+					continue
+				fi
+				debug 2 "$funcname(): [$message] \$pid: '$pid' disappeared"
+				if [ -z "$_disappeared_pids" ]; then
+					_disappeared_pids=$pid
+				else
+					_disappeared_pids="$_disappeared_pids $pid"
+				fi
+				flag=$(( flag + 1 ))
+			done
+			# if everything checks out, get on with our business
+			if [ $flag -eq 0 ]; then
+				debug 7 "$funcname(): [$message] still children running, looping"
+				continue
+			fi
+
+			# remove $_disappeared_pids from $running_pids
+			for pid in $_disappeared_pids; do
+				case $running_pids in
+				$pid)
+					running_pids=""
+					;;
+				$pid" "*)
+					running_pids=${running_pids#$pid }
+					;;
+				*" "$pid)
+					running_pids=${running_pids% $pid}
+					;;
+				*)
+					# since $_disappeared_pids is built from
+					# $running_pids, which hasn't been modified since
+					# $_disappeared_pids is built, we can safely
+					# assume the pid in question is in the middle
+					# without the "expensive" glob-for-middle here
+					var=${running_pids#* $pid } # RHS
+					running_pids=${running_pids% $pid *} # LHS
+					running_pids="$running_pids $var"
+					;;
+				esac
+				lifetime_disappeared=$(( lifetime_disappeared + 1 ))
+				# and add it to $disappeared_pids
+				case $disappeared_pids in
+				"")
+					disappeared_pids=$pid
+					;;
+				$pid | $pid" "* | *" "$pid | *" "$pid" "* )
+					# only item | already in front | .. end | .. middle
+					;;
+				*)
+					disappeared_pids="$disappeared_pids $pid"
+					;;
+				esac
+			done
+		fi # $currently_running -gt 0
+
+		if [ $currently_pending -gt 0 ]; then
+			debug 7 "$funcname(): [$message] still children pending, looping"
 			continue
 		fi
 		if [ $currently_signaled -gt 0 ]; then
-			# debug 7 "$funcname(): [$message] still children signaled"
+			debug 7 "$funcname(): [$message] still children signaled, looping"
 			continue
 		fi
 		if [ $lifetime_started_total -ne $lifetime_ended_total ]; then
-			# debug 7 "$funcname(): [$mismatch] in lifetime total!?"
+			debug 7 "$funcname(): [$message] mismatch in lifetime total, looping"
 			continue
 		fi
 		if [ $teardown -eq 0 ]; then
+			debug 7 "$funcname(): [$message] not in teardown mode, looping"
 			continue
 		fi
 
 		warnx "$funcname(): [$message] read failed and looks like nothing left to do"
-		break
+		#break
+		continue
 
 	done # while :; # top level
 
@@ -402,6 +572,9 @@ IPC_STOP()
 	local funcname=IPC_STOP
 	local message=WAIT
 	local pid
+	local backoff_amount=0
+	local backoff_attempts=0
+	local backoff_max_attempts=10
 
 	# force a subshell so we can stop our own instantiation
 	# without otherwise stopping the calling script.
@@ -416,10 +589,21 @@ IPC_STOP()
 
 		# debug 13 "$funcname(): [$message] -> '$pid'"
 		# debug 12 "$funcname(): [$pid] [$message] sending message to fifo"
-		if ! echo "$message $pid" >>"$IPC_FIFO"; then
-			warnx "$funcname(): [$pid] [$message] failed sending message"
-			return 1
-		fi
+		backoff_amount=0
+		backoff_attempts=0
+		until echo "$message $pid" >>"$IPC_FIFO"; do
+			if [ $backoff_attempts -gt $backoff_max_attempts ]; then
+				warnx "$funcname(): [$pid] [$message] failed sending message after \$backoff_attempts: '$backoff_attempts'"
+				return 1
+			fi
+			warnx "$funcname(): [$pid] [$message] could not write to fifo, backing off by '$backoff_amount'"
+			if ! sleep "$backoff_amount"; then
+				warnx "$funcname(): [$pid] [$message] failed backoff sleep.  \$backoff_amount: '$backoff_amount'"
+				return 1
+			fi
+			backoff_attempts=$(( backoff_attempts + 1 ))
+			backoff_amount=$(( backoff_amount + 1 ))
+		done
 		# debug 13 "$funcname(): [$pid] [$message] logging message"
 		## echo "$message $pid $funcname" >>"ipcdir/sendlog"
 		# debug 8 "$funcname(): [$pid] [$message] pausing myself with SIGSTOP"
@@ -461,6 +645,10 @@ IPC_CHILD()
 	local message pid
 	local oldumask
 	local retval
+	local backoff_amount=0
+	local backoff_attempts=0
+	local backoff_max_attempts=10 # iterations, not seconds
+	local var
 	local umask=0777
 
 	# in the current implementation this is effectively the same as '$$' but
@@ -475,7 +663,23 @@ IPC_CHILD()
 	fi
 	message=PENDING
 	# debug 14 "$funcname(): [$pid] [$message] 1: sending message to fifo"
-	echo "$message $pid" >>"$IPC_FIFO"
+
+	backoff_amount=0
+	backoff_attempts=0
+	until echo "$message $pid" >>"$IPC_FIFO"; do
+		if [ $backoff_attempts -gt $backoff_max_attempts ]; then
+			warnx "$funcname(): [$pid] [$message] failed sending message after \$backoff_attempts: '$backoff_attempts'"
+			return 1
+		fi
+		warnx "$funcname(): [$pid] [$message] could not write to fifo, backing off by '$backoff_amount'"
+		if ! sleep "$backoff_amount"; then
+			warnx "$funcname(): [$pid] [$message] failed backoff sleep.  \$backoff_amount: '$backoff_amount'"
+			return 1
+		fi
+		backoff_attempts=$(( backoff_attempts + 1 ))
+		backoff_amount=$(( backoff_amount + 1 ))
+	done
+
 	# debug 14 "$funcname(): [$pid] [$message] 2: unblocked from fifo"
 	# debug 16 "$funcname(): [$pid] [$message] 3: adding message to log"
 	# echo "$pid $message $funcname '$@'" >>"ipcdir/sendlog"
@@ -486,6 +690,24 @@ IPC_CHILD()
 
 	until 2>/dev/null >"$IPC_CHILD_LOCK"; do
 		if [ -e "$IPC_TEARDOWN" ]; then
+			message=ABORT
+
+			backoff_amount=0
+			backoff_attempts=0
+			until echo "$message $pid" >>"$IPC_FIFO"; do
+				if [ $backoff_attempts -gt $backoff_max_attempts ]; then
+					warnx "$funcname(): [$pid] [$message] failed sending message after \$backoff_attempts: '$backoff_attempts'"
+					return 1
+				fi
+				warnx "$funcname(): [$pid] [$message] could not write to fifo, backing off by '$backoff_amount'"
+				if ! sleep "$backoff_amount"; then
+					warnx "$funcname(): [$pid] [$message] failed backoff sleep.  \$backoff_amount: '$backoff_amount'"
+					return 1
+				fi
+				backoff_attempts=$(( backoff_attempts + 1 ))
+				backoff_amount=$(( backoff_amount + 1 ))
+			done
+
 			# debug 2 "$funcname(): [$message] saw teardown semaphore, returning"
 			return 0
 		fi
@@ -509,12 +731,28 @@ IPC_CHILD()
 			# debug 14 "$funcname(): [$pid] [$message] 1: sending message to fifo"
 			case $message in
 			END)
-				echo "$message $pid $retval" >>"$IPC_FIFO"
+				var="$message $pid $retval"
 				;;
 			*)
-				echo "$message $pid" >>"$IPC_FIFO"
+				var="$messsage $pid"
 				;;
 			esac
+
+			backoff_amount=0
+			backoff_attempts=0
+			until echo "$message $pid $retval" >>"$IPC_FIFO"; do
+				if [ $backoff_attempts -gt $backoff_max_attempts ]; then
+					warnx "$funcname(): [$pid] [$message] failed sending message after \$backoff_attempts: '$backoff_attempts'"
+					return 1
+				fi
+				warnx "$funcname(): [$pid] [$message] could not write to fifo, backing off by '$backoff_amount'"
+				if ! sleep "$backoff_amount"; then
+					warnx "$funcname(): [$pid] [$message] failed backoff sleep.  \$backoff_amount: '$backoff_amount'"
+					return 1
+				fi
+				backoff_attempts=$(( backoff_attempts + 1 ))
+				backoff_amount=$(( backoff_amount + 1 ))
+			done
 
 			# debug 14 "$funcname(): [$pid] [$message] 2: unblocked from fifo"
 			# debug 16 "$funcname(): [$pid] [$message] 3: adding message to log"
