- include return value of the IPC_CHILD payload in the END fifo message - big rework where now i use a lockfile to keep pending children from   starting: 	- IPC_MASTER makes the file and sets it mode 0000 	- IPC_CHILD temporarily sets its umask to 0000 and then loops on 	  trying to write to the file, which will fail until the file 	  is gone. 	- IPC_MASTER removes the file in place of the old "SIGCONT" to 	  a SIGSTOP'ped IPC_CHILD, allowing a new child to drop one and 	  proceed - IPC_END now gets its SIGCONT when IPC_MASTER has *completed* teardown   actions, not simply as an acknowledgement that IPC_MASTER *received*   the teardown request (we'll see if that has any material effect). - it runs reliably now for the "only ever one IPC_CHILD invoked" case,   which was a tricky corner, so check it in

diff --git a/lib/misc/ipc b/lib/misc/ipc
--- a/lib/misc/ipc
+++ b/lib/misc/ipc
@@ -168,7 +168,9 @@ IPC2_START()
 	local default_child_max=127
 	local default_concurrency=1
 
-	local child_max concurrency
+	local child_lock
+	local child_max
+	local concurrency
 	local fifo
 	local tmpdir
 
@@ -219,12 +221,25 @@ IPC2_START()
 		return 1
 	fi
 
+	child_lock="$tmpdir/child_lock"
+	if ! touch "$child_lock"; then
+		warnx "$funcname(): failed to set \$child_lock: '$child_lock'"
+		return 1
+	fi
+	if ! chmod 0000 "$child_lock"; then
+		warnx "$funcname(): failed to write-protect \$child_lock: '$child_lock'"
+		return 1
+	fi
 	# drop the info file down
 	cat > "$tmpdir/info" <<- EOT
 		readonly IPC_FIFO=$fifo
 		export IPC_FIFO
+		readonly IPC_CHILD_LOCK=$child_lock
+		export IPC_CHILD_LOCK
 		readonly IPC_CONCURRENCY=$concurrency
 		export IPC_CONCURRENCY
+		readonly IPC_TEARDOWN=$tmpdir/teardown
+		export IPC_TEARDOWN
 	EOT
 
 	case $BASH_VERSION in
@@ -246,227 +261,239 @@ IPC2_MASTER()
 {
 	local funcname=IPC2_MASTER
 
-	local children=0
-	local concurrency=$IPC_CONCURRENCY
-	local ended_total=0
-	local flag
-	local flush
+	local currently_running=0
+	local currently_pending=0
+	local currently_signaled=0
+	local currently_unsignaled=0
+	local lifetime_ended_total=0
+	local lifetime_started_total=0
 	local message=INIT
-	local pendings pending_child _pendings
-	local pending_total=0
+	local pending_queue _pending_queue
 	local pid pids
+	local rogue_pid=1
 	local signal=CONT
-	local signaled_queue
-	local kill_queue
-	local unsignaled_queue
-	local started_total=0
+	local signaled_queue _signaled_queue
 	local teardown=0
-	local var
-	local wait_requestors
+	local unsignaled_queue _unsignaled_queue
+	local var var2
+	local wait_requestors _wait_requestors
 
-	
-	debug 1 "$funcname(): [$message]"
-	while read pid message; do
+	if ! pid=$(current_pid); then
+		warnx "$funcname(): failed to get current PID"
+		return 1
+	fi
+	debug 1 "$funcname(): [$message] -> '$pid'"
 
-		while :; do
-
-			debug 1 "$funcname(): [$message] -> '$pid'"
-			debug 13 "$funcname(): [$message] logging message from '$pid'"
-			echo "$pid $message $funcname" >>"ipcdir/recvlog"
-
-			case $message in
-			END)
-				children=$(( children - 1 ))
-				ended_total=$(( ended_total + 1 ))
-				;;
-			FINISH)
-				# FINISH is the IPC2_END version of IPC2_CHILD's START.
-				# it is used to indicate a SIGSTOP'd IPC2_END process
-				# has received its SIGCONT.
-				flag=0
-				_pendings=""
-				debug 3 "$funcname(): [$message] removing \$pid '$pid' from \$wait_requestors '$wait_requestors'"
-				for var in $wait_requestors; do
-					# remove the incoming PID from the wait requestors list
-					# by making a new list populated by all the
-					# pids in $pendings other than the one we have
-					# in our hand now.
-					case $var in
-					$pid)
-						flag=1
-						;;
-					*)
-						case $_pendings in
-						"")
-							_pendings=$var
-							;;
-						*)
-							_pendings="$_pendings $var"
-							;;
-						esac
-						;;
-					esac
-				done
-				if [ $flag -eq 0 ]; then
-					# received a message for a non-pending PID.
-					# XXX: ignore this?  fail?
-					warnx "$funcname(): [$message] received message for non-pending \$pid: '$pid'"
-					return 1
-				fi
-				wait_requestors="$_pendings"
-				debug 3 "$funcname(): [$message] \$wait_requestors is now '$wait_requestors', ensure removal of \$pid: '$pid'"
-				;;
-			PENDING)
-				if [ $teardown -ne 0 ]; then
-					if [ ${#kill_queue} -eq 0 ]; then
-						kill_queue=$pid
-					else
-						kill_queue="$kill_queue $pid"
-					fi
-				else
-					if [ ${#unsignaled_queue} -eq 0 ]; then
-						unsignaled_queue=$pid
-					else
-						unsignaled_queue="$unsignaled_queue $pid"
-					fi
-				fi
-				# add PID to tail of pendings queue
-				debug 3 "$funcname(): [$message] adding \$pid '$pid' to \$pendings '$pendings'"
-				case $pendings in
-				"")
-					pendings=$pid
-					;;
-				*)
-					pendings="$pendings $pid"
-					;;
-				esac
-				debug 4 "$funcname(): [$message] \$pendings is now '$pendings', ensure addition of \$pid: '$pid'"
-				pending_total=$(( pending_total + 1 ))
-				;;
-			START)
-				# PID received our SIGCONT, remove from pending list
-				flag=0
-				_pendings=""
-				debug 16 "$funcname(): [$message] removing \$pid '$pid' from \$pendings '$pendings'"
-				for var in $pendings; do
-					# remove the incoming PID from the pendings list
-					# by making a new list populated by all the
-					# pids in $pendings other than the one we have
-					# in our hand now.
-					case $var in
-					$pid)
-						flag=1
-						;;
-					*)
-						case $_pendings in
-						"")
-							_pendings=$var
-							;;
-						*)
-							_pendings="$_pendings $var"
-							;;
-						esac
-						;;
-					esac
-				done
-				if [ $flag -eq 0 ]; then
-					# received a message message for a non-pending PID.
-					# XXX: ignore this?  fail?
-					warnx "$funcname(): [$message] received message for non-pending \$pid: '$pid'"
-					return 1
-				fi
-				pending_total=$(( pending_total - 1 ))
-				pendings="$_pendings"
-				debug 4 "$funcname(): [$message] \$pendings is now '$pendings', ensure removal of \$pid: '$pid'"
-				children=$(( children + 1 ))
-				started_total=$(( started_total + 1 ))
-				;;
-			WAIT)
-				# any newly seen "START"s on the fifo will be killed,
-				# not stopped.
-				signal=KILL
-				teardown=1
-				debug 3 "$funcname(): [$message] adding \$pid '$pid' to \$wait_requestors '$wait_requestors'"
-				case $wait_requestors in
-				"")
-					wait_requestors=$pid
-					;;
-				*)
-					wait_requestors="$wait_requestors $pid"
-					;;
-				esac
-				debug 4 "$funcname(): [$message] \$wait_requestors is now '$wait_requestors', ensure addition \$pid: '$pid'"
-				;;
-			*)
-				warnx "$funcname(): [$message] ERROR: unknown message"
-				return 1
-				;;
-			esac
-
-			message=WORK
-			debug 2 "$funcname(): [$message] looking for work"
-			if [ $teardown -eq 1 ]; then
-				debug 0 "$funcname(): [$message] teardown mode confirmed"
-				if [ ${#pendings} -gt 0 ]; then
-					# kill all pending children and remove from pending
-					kill -"$signal" $pendings
-					debug 2 "$funcname(): [$message] sent '$signal' to pending children: '$pendings'"
-					pendings=""
-					debug 2 "$funcname(): [$message] cleared pending children list"
-				else
-					debug 2 "$funcname(): [$message] no pending children"
-				fi
-				
-				if [ $children -gt 0 ]; then
-					debug 2 "$funcname(): [$message] \$children -gt 0, need to wait"
-					# still more running children to wait for
-					break
-				else
-					debug 2 "$funcname(): [$message] no running \$children to wait for"
-				fi
-				if [ ${#wait_requestors} -gt 0 ]; then
-					debug 2 "$funcname(): [$message] outstanding \$wait_requestors found"
-					kill -CONT $wait_requestors
-					debug 2 "$funcname(): [$message] sent SIGCONT to \$wait_requestors: '$wait_requestors'"
-					break
-				fi
-				debug 2 "$funcname(): [$message] holy shit we are done! @&@ &@ &@& @& @&&@&@ @"
-				# all done!
-				break 2
-			fi
-
-			if [ $children -ge $concurrency ]; then
-				debug 2 "$funcname(): [$message] at concurrency limit, looping"
-				break
-			fi
-
-			if [ ${#pendings} -eq 0 ]; then
-				debug 2 "$funcname(): [$message] no pending children, looping"
-				break
-			fi
-
-			pid=${pendings%% *}
-			debug 1 "$funcname(): [$message] found a pending child: '$pid', sending it '$signal'"
-			kill -"$signal" $pid
-			debug 2 "$funcname(): [$message] signal '$signal' sent to child '$pid'"
-			# DO NOT remove a child from pendings here, that is done after
-			# we see a 'START' from them, ensuring they got the signal to continue
-			# XXX can i flush multiple here if i check to stay under concurrency?
-			break
-
-		done
+	while :; do
 
 		message=READ
-		debug 10 "$funcname(): [$message] \$children: '$children'"
-		debug 12 "$funcname(): [$message] \$pending_total: '$pending_total', \$started_total: '$started_total', \$ended_total: '$ended_total'"
-		debug 1 "$funcname(): [$message] reading fifo"
+		debug 1 "$funcname(): [$message] beginning to read fifo"
+		while read pid message; do
+
+			while :; do
+
+				debug 1 "$funcname(): [READ] fifo: '$pid' -> [$message]"
+				debug 13 "$funcname(): [$message] logging message from '$pid'"
+				# echo "$pid $message $funcname" >>"ipcdir/recvlog"
+
+				case $message in
+				"END "*[0-9]*)
+					currently_running=$(( currently_running - 1 ))
+					lifetime_ended_total=$(( lifetime_ended_total + 1 ))
+					var=${message##* } # return value of the payload
+					message=${message% $var}
+					if [ $var -ne 0 ]; then
+						warnx "$funcname(): [$message] nonzero return value '$var' from \$pid: '$pid'"
+					fi
+					;;
+				FINISH)
+					# FINISH is the IPC2_END version of IPC2_CHILD's START.
+					# it is used to indicate a SIGSTOP'd IPC2_END process
+					# has received its SIGCONT.
+					rogue_pid=1
+					_wait_requestors=""
+					debug 3 "$funcname(): [$message] removing \$pid '$pid' from \$wait_requestors '$wait_requestors'"
+					for var in $wait_requestors; do
+						# remove the incoming PID from the wait requestors list
+						# by making a new list populated by all the
+						# pids in $wait_requestors other than the one we have
+						# in our hand now.
+						case $var in
+						$pid)
+							rogue_pid=0
+							;;
+						*)
+							case $_wait_requestors in
+							"")
+								_wait_requestors=$var
+								;;
+							*)
+								_wait_requestors="$_wait_requestors $var"
+								;;
+							esac
+							;;
+						esac
+					done
+					if [ $rogue_pid -eq 1 ]; then
+						# received a message for a non-pending PID.
+						# XXX: ignore this?  fail?
+						warnx "$funcname(): [$message] received message for unknown wait requestor \$pid: '$pid'"
+						return 1
+					fi
+					wait_requestors="$_wait_requestors"
+					debug 3 "$funcname(): [$message] \$wait_requestors is now '$wait_requestors', ensure removal of \$pid: '$pid'"
+					;;
+				PENDING)
+					# at the pending stage, the PID is the same as IPC_CHILD's caller
+					# so caring about it is not of significant value.
+					# but we can still keep track of them as unique instances.
+					currently_pending=$(( currently_pending + 1 ))
+					;;
+				"RENAME "*[0-9]*)
+					_signaled_queue=""
+					# remove '$pid' from signaled queue and replace with the
+					# new pid, derived from '$message'
+					var2=${message##* }
+					for var in $signaled_queue; do
+						case $var in
+						$pid)
+							# rename me
+							var=$var2
+							;;
+						esac
+						if [ -z "$_signaled_queue" ]; then
+							_signaled_queue=$var
+						else
+							_signaled_queue="$_signaled_queue $var"
+						fi
+					done
+					;;
+				START)
+					currently_running=$(( currently_running + 1 ))
+					currently_signaled=$(( currently_signaled - 1 ))
+					lifetime_started_total=$(( lifetime_started_total + 1 ))
+					;;
+				WAIT)
+					# - any children already in the $signaled_queue have already
+					# been sent their SIGCONT and already count toward the
+					# running total, so they will continue to be sent SIGCONT
+					# in fell swoops during teardown mode.
+					# - otherwise, the $unsignaled_queue now can be thought of
+					# as a kill_queue.
+					signal=KILL
+					teardown=1
+					if ! >"$IPC_TEARDOWN"; then
+						warnx "$funcname(): [$message] failed to set \$IPC_TEARDOWN file: '$IPC_TEARDOWN'"
+					fi
+					debug 3 "$funcname(): [$message] adding \$pid '$pid' to \$wait_requestors '$wait_requestors'"
+					# XXX check for dupes?
+					if [ -z "$wait_requestors" ]; then
+						wait_requestors=$pid
+					else
+						wait_requestors="$wait_requestors $pid"
+					fi
+					debug 4 "$funcname(): [$message] \$wait_requestors is now '$wait_requestors', ensure addition \$pid: '$pid'"
+					;;
+				*)
+					warnx "$funcname(): [$message] ERROR: unknown message"
+					return 1
+					;;
+				esac
+
+				message=WORK
+				debug 2 "$funcname(): [$message] looking for work"
+				if [ $teardown -eq 1 ]; then
+					debug 0 "$funcname(): [$message] teardown mode confirmed"
+					
+					if [ $currently_running -gt 0 ]; then
+						# still more running children to wait for
+						debug 2 "$funcname(): [$message] \$currently_running -gt 0, need to wait"
+						break
+					else
+						debug 2 "$funcname(): [$message] no running \$currently_running to wait for"
+					fi
+
+					if [ $currently_signaled -gt 0 ]; then
+						debug 2 "$funcname(): [$message] \$currently_running -gt 0, need to wait"
+						break
+					else
+						debug 2 "$funcname(): [$message] no running \$currently_signaled to wait for"
+					fi
+
+					debug 2 "$funcname(): [$message] holy shit we are done! @&@ &@ &@& @& @&&@&@ @"
+					# all done!
+					break 3
+				fi
+
+				if [ $currently_running -ge $IPC_CONCURRENCY ]; then
+					debug 2 "$funcname(): [$message] at concurrency limit: '$IPC_CONCURRENCY', looping"
+					break
+				fi
+
+				if [ $currently_pending -eq 0 ]; then
+					break
+				fi
+
+				if [ -e "$IPC_CHILD_LOCK" ]; then
+					debug 37 "$funcname(): [$message] attempting to remove child lock: '$IPC_CHILD_LOCK'"
+					if ! rm -f "$IPC_CHILD_LOCK"; then
+						warnx "$funcname(): [$message] unable to remove pending child lock: '$IPC_CHILD_LOCK'"
+						return 1
+					fi
+					currently_pending=$(( currently_pending - 1 ))
+					currently_signaled=$(( currently_signaled + 1 ))
+				else
+					debug 2 "$funcname(): [$message] no child lock found"
+				fi
+
+				break
+			done # while :;
+
+			message=STATS
+			debug 10 "$funcname(): [$message] \$currently_running: '$currently_running'"
+			debug 12 "$funcname(): [$message] \$lifetime_started_total: '$lifetime_started_total'"
+			debug 12 "$funcname(): [$message] \$lifetime_ended_total: '$lifetime_ended_total'"
+
+			message=READ
+			debug 1 "$funcname(): [$message] reading fifo"
+			continue 
+
+		done <"$IPC_FIFO"
+
+		message=RECOVER
+		debug 7 "$funcname(): [$message] fell out of the loop because no pending fifo writes to read"
+		debug 10 "$funcname(): [$message] \$currently_running: '$currently_running'"
+		debug 12 "$funcname(): [$message] \$lifetime_started_total: '$lifetime_started_total'"
+		debug 12 "$funcname(): [$message] \$lifetime_ended_total: '$lifetime_ended_total'"
+		
+		if [ $currently_running -gt 0 ]; then
+			debug 7 "$funcname(): [$message] still children running"
+			continue
+		fi
+		if [ $currently_signaled -gt 0 ]; then
+			debug 7 "$funcname(): [$message] still children signaled"
+			continue
+		fi
+		if [ $lifetime_started_total -ne $lifetime_ended_total ]; then
+			debug 7 "$funcname(): [$mismatch] in lifetime total!?"
+			continue
+		fi
+
 		continue
 
-	done <"$IPC_FIFO"
+	done # while :; # top level
 
 	message=COMPLETE
-	debug 18 "$funcname(): [$message] \$pending_total: '$pending_total', \$started_total: '$started_total', \$ended_total: '$ended_total'"
-	debug 1 "$funcname(): [$message] holy shit total victory"
+	if [ ! -z "$wait_requestors" ]; then
+		debug 2 "$funcname(): [$message] outstanding \$wait_requestors found"
+		kill -CONT $wait_requestors
+		debug 2 "$funcname(): [$message] sent SIGCONT to \$wait_requestors: '$wait_requestors'"
+	fi
+
+	debug 10 "$funcname(): [$message] \$currently_running: '$currently_running'"
+	debug 12 "$funcname(): [$message] \$lifetime_started_total: '$lifetime_started_total'"
+	debug 12 "$funcname(): [$message] \$lifetime_ended_total: '$lifetime_ended_total'"
+	debug 1 "$funcname(): [$message] total victory, shutting down"
 	return 0
 }
 
@@ -477,7 +504,10 @@ IPC2_END()
 	local pid
 
 	# force a subshell so we can stop our own instantiation
-	# without otherwise stopping the whole script
+	# without otherwise stopping the whole script.
+	# but don't background it; this function should block
+	# until acknowledged by the master
+	
 	(
 		if ! pid=$(current_pid); then
 			warnx "$funcname(): [$message] failed current_pid(), this child is worthless"
@@ -491,57 +521,86 @@ IPC2_END()
 			return 1
 		fi
 		debug 13 "$funcname(): [$pid] [$message] logging message"
-		echo "$pid $message $funcname" >>"ipcdir/sendlog"
+		## echo "$pid $message $funcname" >>"ipcdir/sendlog"
 		debug 8 "$funcname(): [$pid] [$message] pausing myself with SIGSTOP"
 		kill -STOP "$pid"
-		message=FINISH
-		debug 8 "$funcname(): [$pid] [$message] RECEIVED SIGNAL TO CONTINUE"
-		debug 12 "$funcname(): [$pid] [$message] sending message to fifo"
-		if ! echo "$pid $message" >>"$IPC_FIFO"; then
-			warnx "$funcname(): [$message] failed sending message"
-			return 1
-		fi
-		debug 13 "$funcname(): [$pid] [$message] logging message"
-		echo "$pid $message $funcname" >>"ipcdir/sendlog"
 	);
 
 	return 0
-}
-
+} 
 IPC2_CHILD()
 {
 	local funcname=IPC2_CHILD
-	local pid message
+	local message pid
+	local oldumask
+	local retval
+	local umask=0777
 
-	{
+	# in the current implementation this is effectively the same as '$$' but
+	# i'll burn another current_pid() run and we'll see if it hurts perf at all
+	if ! pid=$(current_pid); then
+		warnx "$funcname(): failed current_pid()"
+		return 1
+	fi
+	if ! oldumask=$(umask); then
+		warnx "$funcname(): [$message] failed to determine current umask"
+		return 1
+	fi
+	message=PENDING
+	debug 14 "$funcname(): [$pid] [$message] 1: sending message to fifo"
+	echo "$pid $message" >>"$IPC_FIFO"
+	debug 14 "$funcname(): [$pid] [$message] 2: unblocked from fifo"
+	debug 16 "$funcname(): [$pid] [$message] 3: adding message to log"
+	# echo "$pid $message $funcname '$@'" >>"ipcdir/sendlog"
+	if ! umask "$umask"; then
+		warnx "$funcname(): [$message] failed to modify umask to '$umask'"
+		return 1
+	fi
 
-		if ! pid=$(current_pid); then
-			warnx "$funcname(): failed current_pid(), this child is worthless"
+	until 2>/dev/null >"$IPC_CHILD_LOCK"; do
+		if [ -e "$IPC_TEARDOWN" ]; then
+			debug 2 "$funcname(): [$message] saw teardown semaphore, returning"
 			return 1
 		fi
-			
-		message=PENDING
+	done
+	debug 13 "$funcname(): [$message] Y: free from child lock"
+	if ! umask "$oldumask"; then
+		warnx "$funcname(): [$message] failed to reset umask to \$oldumask: '$oldumask'"
+		return 1
+	fi
+	message=START
+	{
+		if ! pid=$(current_pid); then
+			warnx "$funcname(): failed current_pid(), child now worthless"
+			return 1
+		fi
+
+		debug 14 "$funcname(): [$pid] [$message]"
 		while :; do
 
+			# same block as above
 			debug 14 "$funcname(): [$pid] [$message] 1: sending message to fifo"
-			echo "$pid $message" >>"$IPC_FIFO"
+			case $message in
+			END)
+				echo "$pid $message $retval" >>"$IPC_FIFO"
+				;;
+			*)
+				echo "$pid $message" >>"$IPC_FIFO"
+				;;
+			esac
+
 			debug 14 "$funcname(): [$pid] [$message] 2: unblocked from fifo"
 			debug 16 "$funcname(): [$pid] [$message] 3: adding message to log"
-			echo "$pid $message $funcname '$@'" >>"ipcdir/sendlog"
+			# echo "$pid $message $funcname '$@'" >>"ipcdir/sendlog"
 
 			case $message in
-			PENDING)
-				debug 19 "$funcname(): [$pid] [$message] 4: pausing myself with SIGSTOP"
-				kill -STOP "$pid"
-				debug 16 "$funcname(): [$pid] [$message] 5: RECEIVED SIGNAL TO CONTINUE"
-				message=START
-				;;
 			START)
-				# catch error
 				debug 11 "$funcname(): [$pid] [$message] 4: executing workload '$@'"
 				if eval "$@"; then
+					retval=$?
 					debug 11 "$funcname(): [$pid] [$message] 5: finished workload '$@'"
 				else
+					retval=$?
 					warnx "$funcname(): [$pid] [$message]: workload failed: '$@'"
 				fi
 				message=END
@@ -549,9 +608,11 @@ IPC2_CHILD()
 			END)
 				break
 				;;
+			*)
+				warnx "$funcname(): [$pid] [$pid]: unknown \$message: '$message'"
+				return 1
 			esac
 		done
-
 	}&
 
 	return 0
